export const ActionTypes = {
  SET_CATEGORY: "SET_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  REMOVE_SELECTED_CATEGORY: "REMOVE_SLECTED_CATEGORY",
};
